### ISSUE TITLE
Expose surrounding cells when double-clicking a number next to the correct amount of flags

### ISSUE THREAD

**Issue by discorddioxin** [Lexyth/SweeperOfMine#10]
**Reproduce**
1. Play until numbers are exposed
2. Place flags next to cell with number
  a. If the number is 2, place 2 flags around the cell
3. Double-click the number cell with flags around it

**Expected**
* Expose the non-flagged cells surrounding the number cell

**Actual**
* Nothing happens

**Comment by Lexyth** [comment]
Thanks, will try to add it for the next push. Might be later though, since there are many reworks and issues already.
