### ISSUE TITLE
Still able to expose bomb on first click

### ISSUE THREAD

**Issue by discorddioxin** [Lexyth/SweeperOfMine#11]
**Reproduce**
1. Click a cell
2. Click reset
3. Click the same cell
4. Click reset
5. Repeat

**Expected**
* Unable to encounter a bomb on the first click of a new or restarted game

**Actual**
* Able to encounter a bomb on the first click

**Media**
* https://i.gyazo.com/82c1ec71945c8b3e532d786b930e833c.mp4

**Comment by Lexyth** [comment]
Thank you, this was an oversight on my part. Although i implemented the method to check for this, i used a method that will not yet be called when a field is revealed. Will fix that as soon as possible.
