### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by PanJohnny** [Lexyth/SweeperOfMine#12]
What about adding multiplayer to mine sweeper be cool @Lexyth 
![IMG20201227161906](https://user-images.githubusercontent.com/67548122/104018587-4fd41c80-51ba-11eb-8da6-018d03bedd42.jpg)

**Comment by Lexyth** [comment]
Well... i'll try to add it, but it'll be local multiplayer at best... 
Also may take quite a while. 

Not even sure how it would work right now... all i can think about would be to mark the exposed fields by color and then give each player points according to that... 
We'll see how it goes. 

Thanks for the feedback^^
