### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by j1george** [Lexyth/SweeperOfMine#3]
[here's a resource](https://www.makeareadme.com/) for writing a readme

**Comment by Lexyth** [comment]
Thank you, i‘ll add the readme.👍

**Comment by Lexyth** [comment]
Well... Seems like Markdown Wikitext Markup doesn't show the same way on Github as it did for me... Will fix this in the next Commit.

**Comment by j1george** [comment]
just put a space between # and header content. eg: `#Sweeper Of Mine` -> `# Sweeper Of Mine`. add an additional `#` for each level subheader. eg: `## Description`
