### ISSUE TITLE
Consistent number of bombs

### ISSUE THREAD

**Issue by Ronan-H** [Lexyth/SweeperOfMine#4]
This is kind of subjective, but I think it would be nice to have control over the number of bombs that spawn. The way it is, you could have 1 bomb spawned or you could have 20, it's completely random. Which is fine, but you get much more control over the difficulty and nature of the game if you can specify the number of bombs to spawn.

One easy way to implement this, while making sure every cell has an equal chance of being a bomb, is:
- Let's say we have 100 cells, with indexes 0..99
- We want exactly 10 randomly chosen cells to be bombs and the rest empty
- Add those 100 indexes (integers) to a list
- Shuffle the list (`Collections.shuffle()`)
- The first 10 numbers in the list will be the indexes of our bomb cells

Now we can let the user choose easy (10 bombs), medium (15 bombs), hard (25 bombs) or whatever you want.

**Comment by Lexyth** [comment]
Indeed, i still need to implement the functionality to adjust the difficulty.👍

Thank you.

**Comment by Lexyth** [comment]
Added the majority of this funtionality, except the actual UI to set the number of bombs. Will do that when i rework the View.
