### ISSUE TITLE
The first cell clicked should be guaranteed not to be a bomb

### ISSUE THREAD

**Issue by Ronan-H** [Lexyth/SweeperOfMine#5]
This is a pretty common rule in minesweeper games. It's not a very good user experience to click a random cell and lose instantly. It doesn't happen very often but it is possible.

Once #4 or something similar is implemented (it's kind of a pre-requisite to this issue):

- Wait until the user clicks a cell to decide the bomb locations
- When they do, whatever cell they click must not contain a bomb. From the solution in #4, when you have your list of indexes, simply remove the cell index the user clicked
- Now when you shuffle the list and pick the first *n* indexes,  the cell the user clicked on won't reveal a bomb, because you removed it

**Comment by Lexyth** [comment]
Thank you. I‘ll add that together with the option to select a difficulty.👍

**Comment by Lexyth** [comment]
Sorry, forgot to include the fixed for this issue into the commit message, here is the link to the commit that fixed the issue:
https://github.com/Lexyth/SweeperOfMine/commit/bff8528cd859eacb67f5311ab53406d08823d39d
